# Site settings
title: vectorscores
email: john@johnteskemusic.com
description: >
    A new series of dynamic compositions.
url: "http://vectorscores.org"
twitter_username: johnteske
github_username:  johnteske/vectorscores
website: http://johnteskemusic.com

# Url segments
baseurl: "/vectorscores"
assetsurl: "/assets"

# Jekyll directories
layouts_dir: _jekyll/layouts
data_dir: _jekyll/data
includes_dir: _jekyll/includes

# Build settings
safe: true
markdown: kramdown
sass:
    sass_dir: assets/_sass
    style: compressed
exclude: ["bin"]

# https://github.com/penibelst/jekyll-compress-html
# Compression settings
compress_html:
    clippings: all
    comments: all
    ignore:
        envs: [debug]
